from pydantic import BaseModel, Field
from typing import Optional

class KeyStats(BaseModel):
    """Data model for key stock statistics."""
    open: Optional[str] = Field(None, alias="Open", description="The stock's opening price for the day.")
    day_high: Optional[str] = Field(None, alias="Day High", description="The stock's highest price for the day.")
    day_low: Optional[str] = Field(None, alias="Day Low", description="The stock's lowest price for the day.")
    prev_close: Optional[str] = Field(None, alias="Prev Close", description="The stock's previous closing price.")
    week_52_high: Optional[str] = Field(None, alias="52 Week High", description="The highest price of the stock in the last 52 weeks.")
    week_52_high_date: Optional[str] = Field(None, alias="52 Week High Date", description="The date of the 52-week high.")
    week_52_low: Optional[str] = Field(None, alias="52 Week Low", description="The lowest price of the stock in the last 52 weeks.")
    week_52_low_date: Optional[str] = Field(None, alias="52 Week Low Date", description="The date of the 52-week low.")
    market_cap: Optional[str] = Field(None, alias="Market Cap", description="The total market value of the company's outstanding shares.")
    shares_out: Optional[str] = Field(None, alias="Shares Out", description="The number of a company's shares that are available to be traded on the open market.")
    avg_volume_10_day: Optional[str] = Field(None, alias="10 Day Average Volume", description="The average number of shares traded per day over the last 10 days.")
    dividend: Optional[str] = Field(None, alias="Dividend", description="The dividend per share.")
    dividend_yield: Optional[str] = Field(None, alias="Dividend Yield", description="The company's annual dividend per share as a percentage of the stock's current price.")
    beta: Optional[str] = Field(None, alias="Beta", description="A measure of the volatility of a stock in relation to the overall market.")
    ytd_percent_change: Optional[str] = Field(None, alias="YTD % Change", description="The year-to-date percentage change in the stock price.")
    eps_ttm: Optional[str] = Field(None, alias="EPS (TTM)", description="Earnings per share over the trailing twelve months.")
    pe_ttm: Optional[str] = Field(None, alias="P/E (TTM)", description="Price-to-earnings ratio over the trailing twelve months.")
    fwd_pe_ntm: Optional[str] = Field(None, alias="Fwd P/E (NTM)", description="Forward price-to-earnings ratio for the next twelve months.")
    ebitda_ttm: Optional[str] = Field(None, alias="EBITDA (TTM)", description="Earnings before interest, taxes, depreciation, and amortization over the trailing twelve months.")
    roe_ttm: Optional[str] = Field(None, alias="ROE (TTM)", description="Return on equity over the trailing twelve months.")
    revenue_ttm: Optional[str] = Field(None, alias="Revenue (TTM)", description="Revenue over the trailing twelve months.")
    gross_margin_ttm: Optional[str] = Field(None, alias="Gross Margin (TTM)", description="Gross margin over the trailing twelve months.")
    net_margin_ttm: Optional[str] = Field(None, alias="Net Margin (TTM)", description="Net margin over the trailing twelve months.")
    debt_to_equity_mrq: Optional[str] = Field(None, alias="Debt To Equity (MRQ)", description="Debt-to-equity ratio for the most recent quarter.")
    earnings_date: Optional[str] = Field(None, alias="Earnings Date", description="The date of the next earnings report.")
    ex_div_date: Optional[str] = Field(None, alias="Ex Div Date", description="The ex-dividend date.")
    div_amount: Optional[str] = Field(None, alias="Div Amount", description="The dividend amount.")
    split_date: Optional[str] = Field(None, alias="Split Date", description="The date of the last stock split.")
    split_factor: Optional[str] = Field(None, alias="Split Factor", description="The factor of the last stock split.")
